---

- hosts: all
  become: true
  pre_tasks:
  - name: Install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and add php support
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]
  
  - name: install httpd and php package
    tags: apache, httpd, centos
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (CentOS)
    tags: centos, db, mariadb
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: install mariadb package (Ubuntu)
    tags: ubuntu, db, mariadb
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
