- name: install apache2 and add php support
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu"]

- name: install httpd and php package
  tags: apache, httpd, centos
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution in ["CentOS"]
  
- name: start httpd (CentOS)
  tags: apache, centos, httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"  

- name: change email address for admin
  tags: apache, centos, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin anuj@anuj.com
  when: ansible_distribution == "CentOS"
  register: httpd

- name: restart httpd
  tags: apache, centos, httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed
  
- name: copy default html file for site
  tags: apacehe,apache2,html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644